--CREATE TABLE showList
--(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--name VARCHAR(30));

CREATE TABLE dogBreed
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50));

CREATE TABLE dogInfo
(entryNumber INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50),
ownerName VARCHAR(50),
breed VARCHAR(30),
gender VARCHAR(10),
classSpecialty VARCHAR(20));